version: "3.7"

services:
  back-end:
    image: hollandr/queerfy-backend:latest
    container_name: queerfy-backend
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - APP_PROFILE=sqlserver
  front-end:
    image: hollandr/queerfy-frontend:latest
    container_name: queerfy-frontend
    expose:
      - 3000
    ports:
      - 3000:3000
    


