INSERT INTO users (name, birth_date, rg, cpf, email, password) values ('Rafa', '1999-10-15', '99999', '32321321321312', 'rafael@email.com', 'senha')
INSERT INTO users (name, birth_date, rg, cpf, email, password) values ('Igor', '1999-10-15', '99999', '32321321321312', 'igor@email.com', 'senha')
INSERT INTO users (name, birth_date, rg, cpf, email, password) values ('Lemos', '1999-10-15', '99999', '32321321321312', 'lemos@email.com', 'senha')

insert into property(name, city, description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, haveWifi, haveKitchen, haveSuite, haveGarage, haveAnimals) values ('Linda Casa na Praça', 'São Paulo' ,'Ao Lado da Padaria do Bolsonaro','10000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '1',  'São Paulo', 'SP', '04071007', 'Praça Hussam Eddine Hariri', 'Casa', 'Praça', 'Casa', 'Quarto Inteiro', '2', '2', '1', '1', 'true', 'false', 'false', 'false', 'false')

insert into property(name, city,description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, , state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Linda Casa em Alphaville', 'Penha' ,'Ao Lado da Mansao do Conde','10000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '2', 'São Paulo', 'SP', '08226005', 'Rua Amendoeiras', 'Casa', 'Mansão do Conde', 'Casa', 'Lugar Inteiro', '4', '2', '4', '5', 'true', 'true', 'false', 'true', 'false')

insert into property(name, city,description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Casa Meio Capenga na Zona sul', 'Penha' ,'Local sujeito a Assaltos','10000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '3', 'São Paulo', 'SP', '04413090', 'Rua Belize', 'Casa', 'Posto Petrobras', 'Casa', 'Lugar Inteiro', '2', '1', '2', '3', 'true', 'true', 'false', 'false', 'false')

insert into property(name, city,description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Linda Casa na Praia', 'Rio de Janeiro' ,'Ao Lado da Padaria do Bolsonaro','1000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '1', 'Botafogo', 'SP', '04071007', 'Praça Hussam Eddine Hariri', 'Casa', 'Praça', 'Casa', 'Lugar Inteiro', '2', '2', '1', '1', 'true', 'false', 'false', 'false', 'false')

insert into property(name, city,description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Linda casa em alphaville', 'Rio de Janeiro' ,'Lado da Mansao do Conde','1000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '2', 'Botafogo', 'RJ', '08226005', 'Rua Amendoeiras', 'Casa', 'Mansão do Conde', 'Casa', 'Quarto Inteiro', '2', '1', '1', '2', 'true', 'true', 'false', 'false', 'false')

insert into property(name, city,description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Casa Meio Capenga na Zona sull','Penha' , 'Local sujeito a assaltos','1000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '3', 'São Paulo', 'SP', '04413090', 'Rua Belize', 'Casa', 'Posto Petrobras', 'Casa', 'Quarto Inteiro', '2', '2', '2', '2', 'true', 'true', 'false', 'true', 'true')

insert into property(name, city,description, likes, active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Linda Casa na Praia', 'Sao Paulo' ,'Ao Lado da Padaria do Bolsonaro','1000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '1', 'São Paulo', 'RJ', '04413090', 'Rua Belize', 'Apartamento', 'Posto Petrobras', 'Apartamento', 'Quarto Compartilhado', '3', '3', '1', '2', 'true', 'true', 'false', 'true', 'true')

insert into property(name, city,description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Linda casa em alphaville', 'Sao Paulo' ,'Lado da Mansao do Conde','1000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '2', 'São Paulo', 'SP', '08226005', 'Rua Amendoeiras', 'Apartamento', 'Mansão do Conde', 'Apartamento', 'Lugar Inteiro', '6', '6', '4', '6', 'true', 'true', 'false', 'true', 'true')

insert into property(name, city,description, likes,active, check_in, check_out, daily_price, filter_date, house_img, latitude, longitude, fk_user, state, uf, cep, street, address_complement, reference_point, property_type, space_type, guests_quantity, beds_quantity, room_quantity, bathroom_quantity, have_wifi, have_kitchen, have_suite, have_garage, have_animals) values ('Casa Meio Capenga na Zona sul', 'sao paulo' ,'Local sujeito a Assaltos','1000' ,'true', '2021-10-15', '2021-10-20', '90.00', 'weekend', 'house_img', '-31321332', '-32183123', '3', 'São Paulo', 'SP', '04413090', 'Rua Belize', 'Apartamento', 'Posto Petrobras', 'Apartamento', 'Quarto Inteiro', '2', '2', '1', '1', 'true', 'false', 'false', 'false', 'false')

